import {
  Activity,
  Droplets,
  Heart,
} from "lucide-react";

export const mockData = [
  {
    id: 1,
    type: "Steps",
    icon: Activity,
    value: 10000,
    unit: "steps",
    date: "14/07/2025",
    time: "15:47",
    timeOfDay: "Night",
  },
  {
    id: 2,
    type: "Water Intake",
    icon: Droplets,
    value: 2.1,
    unit: "liters",
    date: "14/07/2025",
    time: "15:16",
    timeOfDay: "Afternoon",
  },
  {
    id: 3,
    type: "Steps",
    icon: Activity,
    value: 12000,
    unit: "steps",
    date: "14/07/2025",
    time: "14:46",
    timeOfDay: "Evening",
  },
  {
    id: 4,
    type: "Heart Rate",
    icon: Heart,
    value: 72,
    unit: "bpm",
    date: "14/07/2025",
    time: "13:46",
    timeOfDay: "Afternoon",
  },
  {
    id: 5,
    type: "Water Intake",
    icon: Droplets,
    value: 1.2,
    unit: "liters",
    date: "14/07/2025",
    time: "12:46",
    timeOfDay: "Morning",
  },
  {
    id: 6,
    type: "Heart Rate",
    icon: Heart,
    value: 72,
    unit: "bpm",
    date: "14/07/2025",
    time: "13:46",
    timeOfDay: "Afternoon",
  },
  {
    id: 7,
    type: "Water Intake",
    icon: Droplets,
    value: 8.2,
    unit: "liters",
    date: "24/07/2025",
    time: "01:46",
    timeOfDay: "Night",
  },
    {
    id: 8,
    type: "Steps",
    icon: Activity,
    value: 3000,
    unit: "steps",
    date: "16/07/2025",
    time: "19:47",
    timeOfDay: "Night",
  },
   {
    id: 9,
    type: "Water Intake",
    icon: Droplets,
    value: 8.2,
    unit: "liters",
    date: "24/07/2025",
    time: "01:46",
    timeOfDay: "Morning",
  },
];
